# - name: Update /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="{{ansible_ssh_host}}{{'\t'}}{{ hostname_name }}{% if hostname_name != hostname_fqdn %}{{'\t'}}{{ hostname_fqdn }}{% endif %}"
#     state=present
#   tags: [configuration,hostname]

# - name: Update lb1 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.19{{'\t'}}lb1{{'\t'}}lb1.gringao.fr"
#     state=present
#   tags: [configuration,hostname]

# - name: Update lb2 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.21{{'\t'}}lb2{{'\t'}}lb2.gringao.fr"
#     state=present
#   tags: [configuration,hostname]

# - name: Update db1 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.22{{'\t'}}db1"
#     state=present
#   tags: [configuration,hostname]

# - name: Update db2 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.25{{'\t'}}db2"
#     state=present
#   tags: [configuration,hostname]

# - name: Update db3 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.26{{'\t'}}db3"
#     state=present
#   tags: [configuration,hostname]

# - name: Update web1 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.27{{'\t'}}web1{{'\t'}}web1.gringao.fr"
#     state=present
#   tags: [configuration,hostname]

# - name: Update web2 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.28{{'\t'}}web2{{'\t'}}web2.gringao.fr"
#     state=present
#   tags: [configuration,hostname]

# - name: Update mail2 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.39{{'\t'}}mail-in-1-p1.gringao.fr{{'\t'}}mail-in-1-p1"
#     state=present
#   tags: [configuration,hostname]

# - name: Update mail2 /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     line="192.168.1.40{{'\t'}}mail-in-1-p2.gringao.fr{{'\t'}}mail-in-1-p2"
#     state=present
#   tags: [configuration,hostname]

############# HADOOP #################

- name: Update /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="{{ansible_ssh_host}}{{'\t'}}{{ hostname_name }}{% if hostname_name != hostname_fqdn %}{{'\t'}}{{ hostname_fqdn }}{% endif %}"
    state=present
  tags: [configuration,hostname]

- name: Update namenode /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.45{{'\t'}}namenode.gringao.fr{{'\t'}}namenode"
    state=present
  tags: [configuration,hostname]

- name: Update secundary-namenode /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.46{{'\t'}}namenode2.gringao.fr{{'\t'}}namenode2"
    state=present
  tags: [configuration,hostname]

- name: Update node1 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.47{{'\t'}}node1.gringao.fr{{'\t'}}node1"
    state=present
  tags: [configuration,hostname]

- name: Update node2 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.44{{'\t'}}node2.gringao.fr{{'\t'}}node2"
    state=present
  tags: [configuration,hostname]

- name: Update node3 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.48{{'\t'}}node3.gringao.fr{{'\t'}}node3"
    state=present
  tags: [configuration,hostname]