- name: Update /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="{{ansible_ssh_host}}{{'\t'}}{{ hostname_name }}{% if hostname_name != hostname_fqdn %}{{'\t'}}{{ hostname_fqdn }}{% endif %}"
    state=present
  tags: [configuration,hostname]

- name: Update lb1 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.19{{'\t'}}lb1{{'\t'}}lb1.gringao.fr"
    state=present
  tags: [configuration,hostname]

- name: Update lb2 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.21{{'\t'}}lb2{{'\t'}}lb2.gringao.fr"
    state=present
  tags: [configuration,hostname]

- name: Update db1 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.22{{'\t'}}db1"
    state=present
  tags: [configuration,hostname]

- name: Update db2 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.25{{'\t'}}db2"
    state=present
  tags: [configuration,hostname]

- name: Update db3 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.26{{'\t'}}db3"
    state=present
  tags: [configuration,hostname]

- name: Update web1 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.27{{'\t'}}web1{{'\t'}}web1.gringao.fr"
    state=present
  tags: [configuration,hostname]

- name: Update web2 /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="192.168.1.28{{'\t'}}web2{{'\t'}}web2.gringao.fr"
    state=present
  tags: [configuration,hostname]
