---
- name: add partner repository into sources list
  apt_repository: repo='deb http://archive.canonical.com/ubuntu {{ ubuntu_version }} partner' state=present

- name: add partner source repository into sources list
  apt_repository: repo='deb-src http://archive.canonical.com/ubuntu {{ ubuntu_version }} partner' state=present

- name: install packages
  apt: name={{ item }} state=present
  with_items: packages
